steps:
# create folder oscmaas-dockerbuild with git repo
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/servicecatalog/oscm-dockerbuild.git']

# build image for ant commands
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gc-ant', '.']
  dir:  'oscm-dockerbuild/gc-ant'

# load libraries form maven repo via ivy
- name: 'gc-ant'
  args: ['-f', 'build-oscmaas.xml', 'BUILD.LIB']
  dir:  'oscm-devruntime/javares'
  id:   'lib'
  
# start compile BES components
- name: 'gc-ant'
  args: ['-f', 'build-oscmaas.xml', 'BUILD.BES']
  dir:  'oscm-devruntime/javares'
  id:   'bes-build'
  waitFor: ['lib']
  
# start compile APP components
- name: 'gc-ant'
  args: ['-f', 'build-oscmaas.xml', 'BUILD.APP']
  dir:  'oscm-devruntime/javares'
  id:   'app-build'
  waitFor: ['lib']

# copy necessary files to docker folders
- name: 'ubuntu'
  args: ['bash', './prepare.sh', '..']
  dir:  'oscm-dockerbuild'
  waitFor: ['bes-build', 'app-build']

# build images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'oscm-gf', '.']
  dir:  'oscm-dockerbuild/oscm-gf'
  id:   'gf-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'oscm-bes', '.']
  dir:  'oscm-dockerbuild/oscm-bes'
  waitFor: ['gf-image']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'oscm-app', '.']
  dir:  'oscm-dockerbuild/oscm-app'
  waitFor: ['gf-image']
 
timeout: '1200s'
images: ['oscm-bes', 'oscm-app']